[saved-emma]
title = "emma" 
db-servers-connect-timeout = 1
db-servers-hosts = "db1,db2"
db-servers-prefered-master = "db1"
mail-from = "stephane@signal18.io"
mail-smtp-addr = "in-v3.mailjet.com:587"
mail-smtp-password = "b362306f5d81a9d5ffff55bcee42094a"
mail-smtp-tls-skip-verify = true
mail-smtp-user = "53b0c2c80298023abf083a106261c789"
mail-to = "emma@signal18.io"
prov-db-cpu-cores = "8"
prov-db-disk-iops = "10000"
prov-db-disk-size = "2"
prov-db-docker-img = "mariadb:10.7"
prov-db-tags = "readonly,docker,linux,innodb,noquerycache,threadpool,slow,ssd,localinfile,nodoublewrite,compressbinlog,noadaptiveflush,relayspacelimit,optimistic,sqlerror"
prov-proxy-disk-size = "1"
prov-proxy-docker-proxysql-img = "proxysql/proxysql:2.4.8"
proxysql = true
proxysql-bootstrap = true
proxysql-servers = "proxysql1,proxysql2"
proxysql-user = "external"
replication-source-name = "emma"
sysbench-binary-path = "/usr/local/bin/sysbench"
sysbench-v1 = true
vault-mount = "kv"
vault-role-id = "bc22f1af-7ce4-e938-46d0-48368beb780d"
vault-secret-id = "91b1a039-1597-54b7-f304-c7b035a29d4e"
