[saved-tata]
title = "tata" 
db-servers-credential = "root:cb4b6a0dba59d4fa4c0c1e757f64f49c4450df5723755867835104ed7666cb5c736a0bb07455439f29a87e3f5b3f1af95e366037eff7da30"
db-servers-hosts = "db1,db2"
prov-db-cpu-cores = "2"
prov-db-disk-size = "700"
prov-db-memory = "1024"
prov-proxy-cpu-cores = "4"
prov-proxy-disk-size = "80"
prov-service-plan = "x2.tiny"
proxysql = true
proxysql-servers = "proxysql1"
proxysql-user = "external"
shardproxy = true
shardproxy-servers = "shardproxy1:3306"
