[saved-tata]
title = "tata" 
db-servers-credential = "root:ae8a4c903eef4de0462bb5aff033c61d827fa4f80e28a11c544f6b3a3187b76a87f426750bf698e00f05f7998727838759843306f0219788"
db-servers-hosts = "db1,db2"
prov-db-cpu-cores = "2"
prov-db-disk-size = "700"
prov-db-memory = "1024"
prov-proxy-cpu-cores = "4"
prov-proxy-disk-size = "80"
prov-service-plan = "x2.tiny"
proxysql = true
proxysql-servers = "proxysql1"
proxysql-user = "external"
shardproxy = true
shardproxy-servers = "shardproxy1:3306"
