[saved-tata]
title = "tata" 
db-servers-credential = "root:d00bd697fe342bd29cc0ff01cc61112b7ee2e3eb50841d94f1aa7032b8ba51a3b16c69dbdb3cf3edfef00e973feb534abab36ac2a011ae85"
db-servers-hosts = "db1,db2"
prov-db-cpu-cores = "2"
prov-db-disk-size = "700"
prov-db-memory = "1024"
prov-proxy-cpu-cores = "4"
prov-proxy-disk-size = "80"
prov-service-plan = "x2.tiny"
proxysql = true
proxysql-servers = "proxysql1"
proxysql-user = "external"
shardproxy = true
shardproxy-servers = "shardproxy1:3306"
