[saved-tata]
title = "tata" 
db-servers-credential = "root:22be831f3d0c75ffa71fccca5ac1dc2bf849da79b70598c58dbcfa07108734fb502e6e97376ee732bd10858dadaaa00106853896e2232639"
db-servers-hosts = "db1,db2"
prov-db-cpu-cores = "2"
prov-db-disk-size = "700"
prov-db-memory = "1024"
prov-proxy-cpu-cores = "4"
prov-proxy-disk-size = "80"
prov-service-plan = "x2.tiny"
proxysql = true
proxysql-servers = "proxysql1"
proxysql-user = "external"
replication-credential = "undefined:f75a60136c2c421fd3d9cb66c0c88d98e2bb6ecd01d8d9e193"
shardproxy = true
shardproxy-servers = "shardproxy1:3306"
