[saved-tata]
title = "tata" 
db-servers-credential = "root:8fd796688bf3f9f20f869920fc6463a078fe0255"
db-servers-hosts = "db1,db2"
prov-db-cpu-cores = "2"
prov-db-disk-size = "700"
prov-db-memory = "1024"
prov-proxy-cpu-cores = "4"
prov-proxy-disk-size = "80"
prov-service-plan = "x2.tiny"
proxysql = true
proxysql-servers = "proxysql1"
proxysql-user = "external"
replication-credential = "root:8b99dbadac976688beda88d6fe73e7338eaaa073"
shardproxy = true
shardproxy-servers = "shardproxy1:3306"
