[saved-tata]
title = "tata" 
db-servers-credential = "root:7bec53a4700db3152c96eecd6bbe3f456e16aac65d4bbe020a2e88908f7563e044b7ebbeeb18f96156c2ad6daab3e1c734d5e2e8c4e58570"
db-servers-hosts = "db1,db2"
prov-db-cpu-cores = "2"
prov-db-disk-size = "700"
prov-db-memory = "1024"
prov-proxy-cpu-cores = "4"
prov-proxy-disk-size = "80"
prov-service-plan = "x2.tiny"
proxysql = true
proxysql-servers = "proxysql1"
proxysql-user = "external"
shardproxy = true
shardproxy-servers = "shardproxy1:3306"
